apiVersion: 1

#deleteDatasources:
#  - name: Graphite
#    orgId: 1

datasources:
- name: Graphite
  type: graphite
  access: proxy
  orgId: 1
  url: http://graphite:80
  basicAuth: true
  basicAuthUser: admin
  basicAuthPassword: status2018
  withCredentials: false
  isDefault: true
  jsonData:
     graphiteVersion: "0.9"
     tlsAuth: false
     tlsAuthWithCACert: false
  version: 1
  editable: false
