---
- name: Creates /docker/netdata directory
  file:
    path: "/docker/netdata"
    state: directory

- name: Check existence of monitor_host variable
  fail:
    msg: "Provide domain monitoring host."
  when: monitor_host is not defined

- name: Create netdata configuration
  template:
    src: templates/netdata.conf
    dest: /docker/netdata/netdata.conf
    owner: root
    group: root
    mode: 0644

- name: Start netdata container for monitoring
  docker_container:
    name: netdata
    image: titpetric/netdata:latest
    state: started
    recreate: true
    pull: true
    restart_policy: always
    ports:
      # TODO: This is read-only, but it still needs some auth.
      - '0.0.0.0:80:19999'
      # WARNING: requires change in netdata.conf
      - '127.0.0.1:8125:8125/udp'
    volumes:
      - '/proc:/host/proc:ro'
      - '/sys:/host/sys:ro'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/docker/netdata:/etc/netdata'
    capabilities:
      - 'SYS_PTRACE'
